### ISSUE TITLE
Configuration testing tool is not opening when I create a an existing component

### ISSUE THREAD

**Issue by cooskun** [Infomaker/NPWriterDevKit#4]
I created a component with textanalyzer name, id is se.infomaker.textanalyzer as well. Component was exist already. When I try to open configuration testing tool I get an error that says "Uncaught Error: An item with reference "se.infomaker.textanalyzer" already exists.". And, it doesn't open. Also I can't edit this existing id unfortunately.

**Comment by dannelundqvist** [comment]
Hi,
This is most probably not a problem with NPWriterDevKit. From your description it seems you have a broken configuration saved in local storage. If that is the case you can go into developer tools and empty local storage to get rid of the problem.
